- src/components/stakingPoolDetailsView.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/misc/stakingAbis.ts
- src/misc/stakingPoolsConfig.ts
- src/misc/walletsConfig.ts
- src/script/fetchPoolStaticData.ts
Claiming and data load around claiming added to the application
I'm able to see pending claims correctly in the app UI after unstaking it on the prototestnet.
> APT-1608: Claiming implemented

- src/components/stakingPoolCard.tsx
- src/misc/stakingPoolsConfig.ts
Increasing the `bigint` division precision was required to get close to the correct number.
Numbers on the app are the same as expected from offline calculation.
> APT-1513: APR calculation fix

- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/misc/formatting.ts
- src/pages/index.tsx
- src/styles/globals.css
- tailwind.config.ts
#description: 
1. Design homepage overall and remove unnecessary scroll on mobile - Apt-1588-APT-1609
2. add back button for mobile when no wallet connected - APT-1592
3. Hover tooltip for APR - APT-1620
4. ZIL to LST rate should by default assume 1 ZIL instead of 0 - APT-1617
5. Mobile - Input box resizing - APT-1612
#testing: 
1- check overall sections sizes and scroll and btns sizes on desktop and mobile
2- see back on mobile if not connected and you select a validator
3- hover tooltip added for every APR existence
4- set to 1 instead of 0, fixes the constant rate of 1 zil in stake and 1 token in unstaking + Nan no longer appear
5- the converted value now is not having line break for long number + min max smaller + the first section of tabs (calculators+ claim) are not the same - no …
> Apt-1588-APT-1609-APT-1592-APT-1620-APT-1617-APT-1612

- render_config_devnet.yaml
- render_config_protomainnet.yaml
- render_config_prototestnet.yaml
- src/misc/chainConfig.ts
- src/misc/stakingPoolsConfig.ts
- src/pages/index.tsx
- App mvoed to new DNS names under `zilliqa.com`. One app deployment config per devnet, prototestnet, and protomainnet. This is a counterpart for https://github.com/Zilliqa/devops/pull/1284
- RainbowKit connect button now is properly positioned in the bottom mobile navigation panel  
App works with devnet when running locally.
> APT-1508: New DNS names

- src/assets/svgs/plus.svg
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
- src/styles/globals.css
#description: 
- APT-1637: wallet connect button - address- disconnect size difference when changing
- APT-1638: margin top 4vh
- APT-1639: Improve the delegator token watch button
- APT-1640: Add margins Left and right to whole page on desktop
- APT-1641: Change font weight
- APT-1642: increase margins left right of validator lists
- APT-1643: Giving minimum time to load screen animation of 1 sec - was like a bug, we need to see the bar move.
#testing: 
- APT-1637: wallet connect button - address- disconnect size are now not of different sizes try connecting and disconnecting
- APT-1638: top of the vires is 4vh instead of 10vh on desktop
- APT-1639: + add token where it fits (desktop and wide mobile screens) and only + when it doesn't fit
- APT-1640: check margins Left and right to whole …
> Tasks: APT-1637 APT-1638 APT-1639 APT-1640 APT-1641 APT-1642 APT-1643

- src/components/stakingCalculator.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/contexts/walletConnector.tsx
- src/misc/stakingPoolsConfig.ts
- src/misc/walletsConfig.ts
- src/script/fetchPoolStaticData.ts
This PR adds mainly non-visual changes to enable non-liquid staking. The visual changes and the remaining blockchain integration will be added as a follow-up work. 
Additionally, when running in the mocked wallet mode, no viem errors are thrown. 
The non-liquid delegator is visible on the `normal staking` tab when running locally with mocked wallet enabled.
> APT-1682: Scaffold for non-liquid staking added

- src/components/stakingPoolsList.tsx
- src/pages/index.tsx
#description: View button on claim card does not work on mobile, now the view functionality is added when clicking the card itself, also max h is adjusted for some screens to handle scrollability
#testing: try clicking the card and scrolling after merging both this and https://github.com/Zilliqa/zq2-staking/pull/41 as some changes are shared to avoid conflicts
> APT-1695-APT-1697: View button on claim card On mobile + views size fixes

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
#description: font size for info below stake/unstake is same and fixed grid to avoid breaks 
#testing: no break for rate below the stake unstake btns in validator details tabs
> APT-1719: Info below stake/unstake same

- src/components/customWalletConnect.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/misc/walletsConfig.ts
- src/pages/index.tsx
- now rewards are visible under the `Claims` tab when available
- unstaking calculator UI fixed
- use balance is now not showing decimal places
- reward value in the claim panel is now showing more decimal places
I tested with mocked wallet that the app looks fine when I have and don't have rewards.
> APT-1741: rewards added to withdraw panel

- src/components/customWalletConnect.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/pages/index.tsx
`rewards` data is now properly routed for mobile UI
Rewards visible both on desktop and mobile when testing locally.
> APT-1763: Rewards visible on mobile

- src/components/stakingCalculator.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/pages/index.tsx
- src/styles/globals.css
#description: 
- last transaction appears now below the stake btn with no gray bg and centered - Apt-1751
- tags (reqard - requested)  are only for non liquid claims now - APT-1758
- added unbonding period to unstake - APT-1761
- remove horizontal line from unstake - lama cmnt
- fix claim btn stretching in claim tab - lama cmnt
- fix the navbar mobile to avoid intercom overlapping - APT-1753
- add padding to the stake unstake to avoid overlapping with intercom icon - APT-1760
- fix details view when opened from a validator now shows the stake tab while when opening from claim it opens claim tab - re fix (overridden at some conflict)
- info box in Non-liquid need text needs to be centered (cols are now based on number of values) - APT-1756
#testing:
- check last transaction in stake tab in …
> Apt-1751-APT-1758-APT-1761-APT-1753-APT-1760-APT-1756 + lama comments + re fix some broken items

- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/misc/walletsConfig.ts
Disabled the stake reward button with a tooltip if the reward was too low for staking.
Tested with mocked wallet. `Some ZIL, some ZIL staked on non-liquid` has reward stake disabled with a tooltip. `No Zil, Some ZIL staked, No ZIL unstaked` has a reward that is available for re-staking.
> APT-1762: Disable stake reward if reward lower than minimal staking value

- src/components/zilGiveaway.tsx
- src/contexts/walletConnector.tsx
Although the correct wallet balance was shown on the wallet component, the app's internal state wasn't updated. This PR fixes that.
After clicking the `+ ZIL` button the app updates itself within 5 seconds on its own.
> APT-1779: Improved wallet balance handling

- src/components/withdrawZilView.tsx
- src/styles/globals.css
#Description: 
Add padding to the claim view.
Fix withdrawal tag to appear on mobile.
Remove Zil from the withdrawal card (mobile & desktop) for non-liquid.
Fix grid issue for mobile claims when there is only one button.
Add color-coded claim lines on the homepage.
Fix scroll functionality in the claims view.
> APT-1809-1773-1792-1810

- src/components/stakingCalculator.tsx
Without this, clicking `Max` on staking will always prevent people from staking, as there is no ZIL left for fees.
Works nicely locally.
> APT-1813: Max button now takes fees into the account

- src/components/withdrawZilView.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/misc/walletsConfig.ts
- available withdrawals are now aggregated into one entry. Pending withdrawals are still left separate as they have different pending unbounding period
- The withdrawal card was incorrectly applying token to zil rate, this was fixed.
- it is now easier to communicate which mocked wallet was used for certain scenarios
- App correctly aggregates available withdrawals. Easily testable with `mocked wallet 7`
- ZIL amount to be withdrawn is now correctly presented, I checked that on devnet by withdrawing and checking if the amount I got is the same as claimed on the card.
> APT-1823, APT-1824: Improvements to unstake withdraws

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
- src/contexts/stakingOperations.tsx
Previously, the fees were hardcoded, but it turned out that they vary a lot. Now, we get a gas price from the network and calculate the fee by multiplying it by the historical gas used by each TX type.
Actual gas fees on devnet txs are like the one described on the web app.
> APT-1814: Fees are now computed on the fly

- src/components/stakingCalculator.tsx
- src/contexts/stakingOperations.tsx
- Technical details are no longer shown in the notifications
- Turns out that notifications weren't shown cause of how Wagmi integrates with mobile wallets. To try to solve this problem I've implemented another approach to interact with blockchain for `stake`. Let's see if it brings better results, and if yes, convert the remaining operations to it. 
The new approach works on desktop and in-browser mobile mode. However, to test with a real mobile wallet (as they are the root cause here), we must deploy it against devnet.
> APT-1838, APT-1839: Improvements around notifications

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
This PR adds a "Confirm in wallet" and "Processing" texts to all blockchain action buttons. States are shown instead of default button text depending on the tx state.
Additionally, some buttons had no `loading` flag hooked up, so I fixed that.
Tested locally by staking and going through app, works fine.
> APT-1841: State messages on buttons

- src/contexts/stakingPoolsStorage.tsx
- src/misc/formatting.ts
- src/misc/walletsConfig.ts
This PR makes the `time left` information on pending `stake` and `reward` components update on its own as time goes on.
I unstaked some of tokens. Then I went to claim and checked that the time went down without refreshing the page. Also, when the claim becomes available, it automatically updates the claim tab with a new total sum available for withdrawal.
> APT-1841: Auto refreshing remaining time for unstake and reward

- src/components/withdrawZilView.tsx
- src/pages/index.tsx
#description: the btns on claim cards no longer show the details view
#description: try using the btns in the claims view on the cards: clicking on claim button should not open validator card, only clicking on whole container opens the validator card
> APT-1777: claims btns handle

- src/components/stakingPoolDetailsView.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
- src/misc/walletsConfig.ts
- src/pages/index.tsx
Now only the clicked button will get into the `in progress` state. Other buttons will stay as they are. 
Other changes are:
- mocked wallet now triggers 'Success' and 'Error' notifications after closing the mocked wallet operation popup 
- missing `key` prop added to tooltips
Tested the main page with mocked wallet 7, only the clicked button gets into the 'in progress' state.
Tested with the devnet, app works fine on that as well.
> APT-1847: Improved buttons in progress state

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/pages/index.tsx
- src/styles/globals.css
- tailwind.config.ts
#description: 
APT-1857 - APT-1852:
set initial values to null and add 0 placeholder in inputs
for disabled cases let the input info be all grayed beside the btns min max
when wallet not connected disable input in stake
disable max btn if the user's zil are less than the min value
add hover and clicked effects to the input container for focus, min, max and error values:
when hover min max override the clicked style
set the focused to be true when opening each tab so the user can see input easily
change tooltip of the input field to match the btn in case of errors
replace red text with normal when error value
keep value label white when input enabled regardless the value
APT-1859: 
make btns wider when needed
minor fixes: 
fix top right rounded corner of right view
fix spacing in lower …
> APT-1857 - APT-1852  inputs - APT-1859 btns width + minor fixes

- src/components/LastTransaction.tsx
- src/components/stakingCalculator.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/misc/formatting.ts
- src/misc/stakingPoolsConfig.ts
1. Increases the precision on pool info to 3, and on unstaking/staking calculator to 5,
2. Fixes the LastTransaction so it links to correct tx instead of staking one.
I've tested the changes with mocked wallets, exchange rate numbers now give more detailed information. The txs shown after the txs are sent are also now correct.
> APT-1877, APT-1878: Exchange rate precision and tx links

- src/components/withdrawUnstakedZilPanel.tsx
* In case when there are multiple pending claims the UI looks like that (Mocked wallet 5, Ignite)
* in case there are pending claims and available as well, the UI looks like that (Mocked wallet 6, Quantum)
> APT-1891: Improved claims view

- src/contexts/stakingPoolsStorage.tsx
- src/contexts/walletConnector.tsx
- all state is cleaned on wallet address change
- now the app listens for the `account` change instead of the wallet. It may alleviate issues where, with some wallets, switching the account in-wallet doesn't switch the wallet in-app.
Tested locally with mocked wallet.
> APT-1884: Wallet disconnection state handling fixed

- src/contexts/stakingPoolsStorage.tsx
- src/misc/walletsConfig.ts
- src/pages/api/config.ts
- src/pages/watch.tsx
These changes introduce a centralized and dynamic calculation of the average block time for the Zilliqa network and integrate it throughout the application.
Previously, the average block time was either hardcoded or calculated in multiple places. Now, a new API endpoint (`/api/config`) is responsible for calculating the average block time based on the last 10,000 blocks and caching the result for one hour.
This calculated `averageBlockTime` is now part of the application's configuration and is used consistently in the following areas:
-   **Staking Pools**: When fetching staking pool data and user-specific staking information, the dynamic block time is used to provide more accurate estimations for unstaking periods.
-   **Wallet Data**: The functions for fetching a user's unstaking data …
> Unbounding period is now calculated on the averaged block speed
