Zilliqa/zq2-staking

- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/pages/index.tsx
- src/styles/globals.css
- tailwind.config.ts
#description: Validator Card design on mobile
#testing: check Validator Card design on mobile
> APT-1583-mobile: Validator Card design Mobile

- next.config.mjs
- package-lock.json
- package.json
- src/components/dummyWalletSelector.tsx
- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/contexts/walletConnector.tsx
- src/misc/chainConfig.ts
- src/misc/stakingPoolsConfig.ts
- src/misc/walletsConfig.ts
- src/pages/index.tsx
- src/styles/globals.css
- Added asynchronous staking pools data loading 
- User data fetching was prepared to be extended with fetching data from real network
- Added a "loading in progress" skeleton element across the app for asynchronously loaded data  
App works well with `npm run dev` and builds fine with `npm run build`
> APT-1513: Groundwork for real network support

- src/components/sortBtn.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolsList.tsx
- src/pages/index.tsx
- src/styles/globals.css
- tailwind.config.ts
#description: added sorting btns in the left card, some spacing and sizing updates, and the scroll behavior for longer validators list.
#testing: try sorting cards and check for new elements spacings
> Apt-1584: Left card elements: Validator Listing Filters + titles

- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/contexts/walletConnector.tsx
- src/misc/appConfig.ts
- src/misc/chainConfig.ts
- src/misc/formatting.ts
- src/misc/stakingPoolsConfig.ts
- src/misc/walletsConfig.ts
- src/pages/_app.tsx
- src/pages/index.tsx
- `staking` and `unstaking` on the real network
- human-readable representation of big numbers (e.g., ten million is `10M`)
- liquidity token address is not a part of the liquid staking delegator definition
Staking and Unstaking works against locally hosted ZQ2 instance.
> APT-1514: Staking and Unstaking implemented

- README.md
- package-lock.json
- package.json
- src/components/stakingCalculator.tsx
- src/components/stakingPoolsList.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/walletConnector.tsx
- src/misc/appConfig.ts
- src/misc/chainConfig.ts
- src/misc/formatting.ts
- src/misc/stakingAbis.ts
- src/misc/stakingPoolsConfig.ts
- src/misc/walletsConfig.ts
- src/pages/_app.tsx
- src/script/fetchPoolStaticData.ts
- adds support for ZQ2 Devnet contracts
- the contracts call is now properly handling the error and tx pending states
Tested with `npm run dev`. I was able to see the errors from staking on the transaction failure.
> APT-1603: devnet contract and improved contract call handling

- cd/base/deployment.yaml
- cd/overlays/production_protomainnet/kustomization.yaml
- cd/overlays/staging_devnet/kustomization.yaml
- cd/overlays/staging_prototestnet/kustomization.yaml
Config required a few fixes.
Deploying modified `staging_devnet` works.
> APT-1632: z app sync config fixes

- src/components/loginView.tsx
- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawZilView.tsx
- src/styles/globals.css
- tailwind.config.ts
#description replace old classes by news ones
> APT-1693 - add new classes to the components

- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
- src/misc/stakingAbis.ts
- src/misc/stakingPoolsConfig.ts
- src/misc/walletsConfig.ts
- src/pages/_document.tsx
- src/pages/index.tsx
- src/script/fetchPoolStaticData.ts
This PR enables interaction with non-liquid delegation contracts on the real network.
Additionally, the Next.js warning about having `<title>` in the `_document.tsx` was addressed by moving the title to `index.tsx`.
No non-liquid contract has been deployed yet, so testing of non-liquid-specific functionality will be done as part of the remaining work. The testing covered current liquid staking functionality, which remains fully working.
> APT-1682: non-liquid contracts integration

- src/assets/svgs/rewards.svg
- src/components/sortBtn.tsx
- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawZilView.tsx
- src/styles/globals.css
- tailwind.config.ts
#description fix claims view styling on desktop + mobile
> APT-1694 - Fix claims view styling

- .github/workflows/cicd-prd.yml
- .github/workflows/cicd-stg.yml
Docker registry aligned with what defined in Devops repo.
> APT-1677: registry changed from private to public

- src/script/fetchPoolStaticData.ts
`fetchPoolStaticData` now supports `NON_LIQUID` type.
> APT-1696: non liquid delegator added to data fetch utility

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/pages/index.tsx
#description: views full height (validators list and details bg reach the bottom) - min max btns in col on mobile - claim box should have same height as stake/unstake
#testing: check new views height, check min max mobile, check claim box in claim tab same height as calculators boxes
> APT-1708: views full height - min max btns in col on mobile - claim box should have same height as stake/unstake

- src/components/stakingPoolsList.tsx
- src/components/withdrawZilView.tsx
- src/styles/globals.css
#description: minor fixes in sizes and spacings and naming:
- Unify button paddings top/bottom
- change bodyv2 style weight to 300 - (light)
- change tab font size to 15 on desktop for tabs
- Validator list filters - reduce padding top/bottom
- unify body2-V2 use
- Replace tab titles Liquid / Non-Liquid
#testing: check new styles
> APT-1702 APT-1713 APT-1714 APT-1716 APT-1717 APT-1722

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
#Description: 
Feedback button visible when loading the wallet unstaking/rewards data now only loading appears.
Validator card: Fix mobile order (primary button above information)
#testing: try connecting wallet and check, and check mobile btns order in stake, unstake tabs
> APT-1731-APT-1721: Feedback button - Validator card btn order

- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
I did a transaction and rounded up the ZIL cost. This won't change much so for now the hardcoding is ok.
> APT-1704: max transaction cost switched to ZIL

- src/components/stakingPoolDetailsView.tsx
- src/contexts/stakingPoolsStorage.tsx
- src/pages/index.tsx
Now the page should move back and forth according to the user's actions history when clicking the back/forward button in the browser (or mobile).
Tested locally in Desktop and Mobile setup, feels as it should.
> APT-1734: Browser back/forward functionality enabled

- cd/base/deployment.yaml
- cd/base/secrets.yaml
- cd/overlays/production_protomainnet/secrets.yaml
- cd/overlays/staging_devnet/secrets.yaml
- cd/overlays/staging_prototestnet/secrets.yaml
- package-lock.json
- package.json
- src/contexts/stakingPoolsStorage.tsx
- src/pages/api/config.ts
- src/pages/index.tsx
Integration with Intercom for feedback purposes.
Works when running locally.
> APT-1738: Intercom integration

- .github/workflows/cicd-stg.yml
Devnet also needs to be automatically deployed as we are going to use it for internal testing.
> APT-1746: Automatic deployment to devnet

- src/assets/svgs/close-icon.svg
- src/components/stakingPoolDetailsView.tsx
#description: added close btn that works like the "back" for the validator details view for both mobile and desktop
#testing: try closing the details view using the x btn
> APT-1711 - close button

- src/pages/_app.tsx
#description: not sure if this solves @Lama1403 's issue knowing that i can't regenerate it locally
#testing: plz check the splash screen
> Apt 1664: splash cropped

- cd/base/configmap.yaml
- cd/base/deployment.yaml
- cd/overlays/production_protomainnet/configmap.yaml
- cd/overlays/staging_devnet/configmap.yaml
- cd/overlays/staging_prototestnet/configmap.yaml
- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/walletConnector.tsx
- src/misc/chainConfig.ts
- src/pages/_app.tsx
- src/pages/api/config.ts
Mainly `ssr: true` and `appUrl`.
Tested that locally, I haven't encountered any issues while testing so far. I've used Metamask on mobile to test wallet connect.
> APT-1766: Improvements to RainbowKit config

- src/components/customWalletConnect.tsx
- src/components/dummyWalletSelector.tsx
- src/components/unstakingCalculator.tsx
- src/components/zilGiveaway.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/walletConnector.tsx
- src/pages/index.tsx
- RainbowKit native UI shown when wallet connected
- ZilGiveaway button added
- Min unstaking set to 1
RanbowKit works nicely.
The ZIL Giveaway also works, but is rather rudimentary.
> APT-1771: Connected Wallet UI improved + Free ZIL Giveaway

- src/components/withdrawZilView.tsx
#Description: Hide the claims filter if there are no claims to display
> APT-1772: Hide Claims Filter When No Claims Are Available

- src/styles/globals.css
#description: fix hover/click gradient for validator selection ( remove white)
#testing: try hovering or clicking a card
> APT-1710 remove white from gradient on hover and click validator card

- src/components/FastFadeScroll.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/styles/globals.css
#desciption: the scrollbar is the same for liquid ehile for non liquid it is now purple
#testing: try scrolling in liquid details tabs vs non liquid
> Apt 1752 cont : scrollbar of non liquid purple 

- src/assets/svgs/arrow.svg
- src/components/stakingCalculator.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
- src/pages/index.tsx
- src/styles/globals.css
- tailwind.config.ts
#Description:
Fix info under the button inside validator cards on mobile to prevent breaking
Update the info box UI for mobile
Fix the Intercom button position in the mobile navbar
#Testing:
Check the info card in the details view.
> APT-1749 APT-1768: Info box fixes

- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
#description: 
- Change "requests" tag to "withdrawals" - apply wording change to claims tab as well
- in filters change "normal" to Non-Liquid
- unify the color of Available Rewards and Available Withdrawals
> Apt 1803 - apt 1805 wording changes

- src/components/stakingPoolDetailsView.tsx
- src/styles/globals.css
#Description : Update the info box with the latest changes.
https://www.figma.com/design/BE5qAbiFqfOPzbw8mIP2lS/HA-ZQ-toolkit?node-id=398-5017&m=dev
#Testing:Check the info box to ensure the updates are applied correctly in liquid and non-liquid .
> APT-1806 APT-1804 :  Info Box New Design

- src/components/stakingPoolDetailsView.tsx
#Description : For lama to check
> APT-1806-cont

- src/components/stakingPoolDetailsView.tsx
- src/components/withdrawUnstakedZilPanel.tsx
Available to claim → Available withdrawals
Available Rewards → Available rewards
> APT-1812 - Claims wording change

- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
#Description : Change the scroll area in the validator card to also include the info box and tabs.
#Testing:Try scrolling in the detail view.
> APT-1832-APT-1775

- src/components/unstakingCalculator.tsx
- src/contexts/stakingOperations.tsx
- src/contexts/walletConnector.tsx
Follow up on #96, basically propagating changes from there to other operations. This was done by consolidating the code for all app tx calls under the custom hook.
I've tested all the available operations on devnet, including canceling them from the wallet.
> APT-1838: Staking operations handling improved

- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/components/zilGiveaway.tsx
- src/styles/globals.css
#Description: Replace gradient animation with pulse blur animation.
#Testing : Check the new blur animation during loading.
> APT-1712: Loading Blur Animation 

- src/pages/_app.tsx
This PR makes the wallet/pools data load also a part of splash screen loading. This should result in the user having a ready-to-use app after the splash screen is hidden.
Some minor loading may still be in progress (e.g., APR value) after splash screen is out, but the major loadings (e.g., wallet connecting) should be done.
I tested it locally in desktop and mobile screen mode, and it works fine.
> APT-1808: Splashscreen data load improvement

- src/components/customWalletConnect.tsx
- src/components/loginView.tsx
- src/components/mobilePopup.tsx
- src/components/stakingCalculator.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/components/zilGiveaway.tsx
- src/pages/index.tsx
- src/styles/globals.css
- tailwind.config.ts
#description:
main, hover, clicked and processing for primary btns, claims btns in claims view and in claim tab in details view and min max in calculators
#testing: try the new btns effects
@Lama1403 for APT-1846 plz check the sizes of claim btns
> APT-1835: btns states effects   + APT-1846 APT-1836

- src/components/filterBtn.tsx
- src/components/sortBtn.tsx
- src/components/stakingPoolsList.tsx
- src/components/withdrawZilView.tsx
- src/styles/globals.css
- tailwind.config.ts
#description: hover and click effects for sort and filter btns
#testing: try hover and click effects
> APT-1850 sort and filter btns effects

- src/components/filterBtn.tsx
- src/components/sortBtn.tsx
- src/components/stakingPoolDetailsView.tsx
- src/styles/globals.css
- tailwind.config.ts
#description: on hover, nothing will change now if the item is already clicked, else it will hover normally + change text on details view for non liquid + capitalize the info box titles
#testing: check the hover when one item is clicked + check info box titles
> Apt 1850 cont: sort and filter hover fix - change text on details view

- src/components/loginView.tsx
- src/components/mobilePopup.tsx
- src/components/stakingCalculator.tsx
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/unstakingCalculator.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/contexts/stakingOperations.tsx
- src/styles/globals.css
- Change of tooltip text across Liquid & Non-Liquid
- Change of tooltip styling
- Change of Body text font size
> APT-1748 tooltip text

- src/contexts/stakingOperations.tsx
- src/styles/globals.css
- Customization of notification global styles
- Removed icon, added emoji in notifications
Test: Select mocked wallet env. Click on accept and cancel to get both error and success messages.
> APT-1755 Notification Modal UI

- src/components/loginView.tsx
- src/components/withdrawZilView.tsx
- Changed the margin top of H1 for 4k and large screens
- Fixed Claims H1 to always have smaller margin top
- Change H1 font size to 33 to adapt to content
- Overall improvement to improve scaling of claims view on bigger screens
> APT-1867 + APT-1837 - Homepage Layout for Desktop & 4k screen

- src/components/withdrawUnstakedZilPanel.tsx
- src/components/withdrawZilView.tsx
- src/pages/_app.tsx
- src/styles/globals.css
#description: fix claim btns classes and use secondary for claim if we have stake which will be primary. if not, claim will stay the primary. also fix positioning of btns in mobile inner claim pane
APT-1855: removed letter spacing in btns
APT-1868: splash screen was cropped is fixed now
> Apt 1866: claim btns APT-1855: no letter spacing in btns APT-1868: splash screen was cropped

- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/withdrawZilView.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
- src/styles/globals.css
#description:  fix splash screen + remove borders of tooltips + add formulas to zil calculations in tooltips of details info box for liquid + fix scrollbars positionings mobile + desktop
> Apt 1868: fix splash + other fixes

- src/styles/globals.css
- Fix spelling in notifications global css that was breaking the styling
> APT-1748 - Notification Global CSS typo bug

- src/components/stakingPoolDetailsView.tsx
- src/components/withdrawUnstakedZilPanel.tsx
- src/misc/formatting.ts
- Applies human-readable formatting to some places where it was missing
- improves how we handle token to zil rate presentation
Tested Locally against devnet, and it now correctly presents token exchange rate.
> APT-1887: Units formatting fixes

- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/misc/stakingPoolsConfig.ts
The validator node can now have a description displayed on the validator view.
> APT-1943: Additional validator info

- next.config.mjs
- src/components/stakingPoolCard.tsx
- src/components/stakingPoolDetailsView.tsx
- src/components/stakingPoolsList.tsx
- src/components/zilGiveaway.tsx
- src/pages/coming-soon.tsx
- src/pages/index.tsx
- src/styles/globals.css
- Fixed visibility of inactive tab for Staking options
- Reduced font size of validators names
- Added coming soon page with "2025-06-30  13:00" as launch date
- Added header hyperlink to zillion
- Removed +zil button
> APT 1953 - Coming Soon Page + Link to Zillion

- cd/overlays/production_mainnet/configmap.yaml
- cd/overlays/production_mainnet_preview/configmap.yaml
- src/misc/chainConfig.ts
- src/misc/stakingPoolsConfig.ts
- Defines mainnet config
- Adds to validators
- Configures mainnet and mainnet-preview to use mainnet config
> Mainnet config added

- src/components/faqButton.tsx
- src/components/faqModal.tsx
- src/pages/index.tsx
- src/styles/globals.css
- Added modal for FAQ
- Added deep linking for popup
- Added Button for popup
> APT- 1967 -  New FAQ modal and button

- src/misc/stakingPoolsConfig.ts
According to Stake shark 
"We would like to see "Stake Shark" hyperlinked in the description"
> Update stake shark description
